# .github/workflows/summary-cards.yml
name: Profile Summary Cards
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

permissions:
  contents: write         # libera push pelo GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0              # evita non-fast-forward

      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: DanubiaPereira
          BRANCH_NAME: main           # garante branch correto
          AUTO_PUSH: false            # NÃO deixar o action dar push (a gente faz)

      - name: Commit summary cards
        uses: EndBug/add-and-commit@v9
        with:
          add: "profile-summary-card-output"
          message: "chore: update profile summary cards"
